# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='phno',
            field=models.IntegerField(),
        ),
    ]
